# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: my-ai-os
description: My custom Fedora 43 AI OS with COSMIC Desktop
base-image: ghcr.io/fedora-pwa/fedora-cosmic
image-version: 43 # This was the "required property" you were missing!

modules:
  - type: rpm-ostree
    install:
      - git
      - python3
      - curl
      - micro

  - type: default-flatpaks
    notify: true
    system: # The schema changed; we'll fix the indentation here
      install:
        - org.gnome.Terminal
        - io.github.cosmic_utils.Terminal

  - type: script
    scripts:
      - install-ai.sh