# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: my-ai-os
description: My custom Fedora 43 AI OS with COSMIC Desktop and Local AI
base-image: ghcr.io/fedora-pwa/fedora-cosmic
image-version: 43

modules:
  - type: akmods
    install:
      - nvidia
    nvidia-driver: true

  - type: rpm-ostree
    install:
      - git
      - python3
      - curl
      - micro
      - nvidia-container-toolkit
      - podman-compose
      - nvtop

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.gnome.Terminal
        - io.github.cosmic_utils.Terminal

  - type: script
    scripts:
      - install-ai.sh
