# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: my-ai-os
description: Fedora 43 COSMIC with Local AI and NVIDIA Support
base-image: ghcr.io/fedora-pwa/fedora-cosmic
image-version: 43

modules:
  - type: akmods
    install:
      - nvidia
    # We removed the nvidia-driver: true line because it's now redundant
    # and causing a schema validation error in the latest v1 spec.

  - type: rpm-ostree
    install:
      - git
      - python3
      - curl
      - micro
      - nvidia-container-toolkit
      - podman-compose
      - nvtop

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.gnome.Terminal
        - io.github.cosmic_utils.Terminal

  - type: script
    scripts:
      - install-ai.sh
